# Site metadata --------------------------------------------------
title: "Frank Nocke"
seotitle: "Frank Nocke • Frontend Javascript Entwickler • Hamburg • Schweiz"

title_separator: "—"
lang: 'de'
email: your-email@example.com
name: "the name of the site"
description: >-
  Frank Nocke
  Master of Computer Science [MSc] • Dipl.-Medieninformatiker [FH]
  Frontend Entwickler • React • JavaScript • NodeJS — Hamburg | Schweiz
  Freelancer in Hamburg, Bottighofen
baseurl: ""
timezone: "Europe/Berlin"
url: "https://nocke.github.io/"
#twitter_username: overn
github_username: nocke
encoding: UTF-8

profile:
  mail: frank[át]nocke.de
  xing: https://www.xing.com/profile/Frank_Nocke
  #stackoverflow: https://stackoverflow.com/users/444255/frank-nocke?tab=topactivity
  stackoverflow: https://stackoverflow.com/cv/react-javascript-frontend-developer-freelancer-hamburg-switzerland
  github: https://github.com/nocke


repository: "nocke/nocke.github.io"

# Site settings --------------------------------------------------
theme: jekyll-theme-hacker
github: [metadata]
layout: default
static: 'https://ssl.webpack.de/static.nocke.de' # TEMPTEMP kinda

# Sass compilation -----------------------------------------------
sass:
    sass_dir: _sass
    style: compressed

# page default ( Front Matter) -----------------------------------
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      canonical_url: 'https://www.nocke.de/foo/foo'
      seo_tag.canonical_url: 'one-two-three'
      author: Frank Nocke
      layout: "default"
      categories: [blog]
      lang: "de"

# Pagination -----------------------------------------------------

#pagination:
#  debug: true
#  enabled: true
#  per_page: 10
#  sort_reverse: true
#  trail:
#    before: 2
#    after: 2

# Build settings -------------------------------------------------
category_dir: /

markdown: kramdown
permalink: /:categories/:year/:month/:title–:slug
#paginate: 3

plugins:
  - jekyll-feed

collections:
  pages:
    output: true
    permalink: /frank-nocke/portfolio/:title/


# ls _site  will be a good idea, to see, what else needs exlcuding
# “Every other directory and file except for those listed above will be copied verbatim to the generated site.“
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - package.json
   - package-lock.json
   - script
   - .asset-cache
   - .gitignore
   - CNAME
   - LICENSE
   - README.me
   - PREP

